pipeline {
    agent any
    
    stages {
        stage('Build') {
            steps {
                sh 'mvn -DskipTest clean package'
            }
        }
    }
    
     stages {
        stage('Test') {
            steps {
                sh 'mvn test'
            }
        }
    }
}


